I have added logic to lookup os.environ 'URL_PREFIX' if exists use it instead of the DEFAULT_PREFIX
app-registry/appr pull request #108
Opened 2023-06-22 15:29 UTC by myselfram

@notjames @joejulian @ant31 
if my understanding is correct this should work, please review and help me merge this code.

Regards,
Ram

2023-06-23 03:09 UTC, notjames approved these changes
Lgtm

2023-06-23 14:02 UTC, myselfram commented
@notjames @joejulian @ant31 @steved @philips @polvi @mtalbot 

What else do I need to do to be able to merge this code change? 
Please help.

Regards,

Ram Srinivasan

2023-06-26 20:38 UTC, myselfram commented
@notjames @joejulian @ant31 @steved @philips @polvi @mtalbot

This is frustrating I was hoping someone would respond.

Please help me with this change request.

Regards,

Ram Srinivsan

2023-06-26 22:42 UTC, notjames commented
@myselfram I'm not sure how much experience you have with github. If I may opine, you're kind of new to it. Taking a look at this project seems to indicate that it's probably a dead project considering no commits/PRs seem to have been done in over 5 years. Moreover, I thought this was a dead project as I thought appr was no longer necessary (I could be wrong there). Nevertheless, you've managed to get some attention of people in this project, but not the right people and it's possible you're not going to get the attention of a maintainer given the length of time this project has been updated. You might be better off forking this project and using your own fork for your needs rather than waiting for someone to commit/merge this PR.

2023-07-05 21:41 UTC, joejulian commented
Also, in the open source world, patience is a must. You pinged me while I was on a 2 week vacation. No service, just trees, water, sea otters, and orcas. I'm not a contributor to this repo so I really have no idea what this PR is about or why it should or shouldn't be included and I really don't need negativity on my return from such a wonderful time away.

Also, as Jim says, this hasn't seen a commit in years. That's not to say that the owner might not accept it, but it would require that they have the time to even take a look. Most folks have day jobs and only maintain these old repos in their spare time.

Give people a break. Stand in their shoes.

2023-07-06 22:29 UTC, notjames commented
> Also, in the open source world, patience is a must. You pinged me while I was on a 2 week vacation. No service, just trees, water, sea otters, and orcas. I'm not a contributor to this repo so I really have no idea what this PR is about or why it should or shouldn't be included and I really don't need negativity on my return from such a wonderful time away.
> 
> Also, as Jim says, this hasn't seen a commit in years. That's not to say that the owner might not accept it, but it would require that they have the time to even take a look. Most folks have day jobs and only maintain these old repos in their spare time.
> 
> Give people a break. Stand in their shoes.

Joe, glad to hear you had a good vacation. Thanks for chiming in. Yeah, I don't know how we got on as contributors. Maybe I just forgot because it was so long ago. Did we work on it when we were at Samsung?

2023-08-15 12:22 UTC, ant31 requested changes

2023-08-15 12:22 UTC, ant31 commented on appr/client.py
> +        if 'URL_PREFIX' in os.environ:
please name it: APPR_URL_PREFIX  and it should be good to merge

2025-03-04 13:23 UTC, merged

2025-03-04 19:44 UTC, myselfram commented on appr/client.py
> +        if 'URL_PREFIX' in os.environ:
done https://github.com/app-registry/appr/pull/109